# WAS Pod가 사용할 PersistentVolumeClaim 정의
# 이 PVC는 petclinic Helm Chart에서 자동 마운트됩니다.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi