# EFS PersistentVolume 정의
# Helm values.yaml에서 설정 값을 주입받아 동적으로 생성됩니다.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv  # PVC에서 참조할 PV 이름
spec:
  capacity:
    storage: {{ .Values.storage.size | default "5Gi" }}  # 의미 없는 값이지만 필수 입력
  volumeMode: Filesystem
  accessModes: {{ toJson .Values.storage.accessModes | default "[\"ReadWriteMany\"]" }}  # 다중 Pod 접근 가능
  persistentVolumeReclaimPolicy: Retain  # 삭제 후에도 PV 유지
  storageClassName: {{ .Values.storage.storageClassName | default "efs-sc" }}  # PVC가 요청할 StorageClass
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.storage.volumeHandle }}  # Helm에서 주입받은 EFS 파일시스템 ID
