# ------------------------------------------------------------
# Service: petclinic-web
# 목적: 외부 또는 클러스터 내부에서 웹 파드에 접근 가능하도록 설정
# ------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: petclinic-web
spec:
  type: {{ .Values.web.service.type | default "ClusterIP" }}  # 외부 노출 시 LoadBalancer로 설정 (기본은 ClusterIP)
  selector:
    app: petclinic-web
  ports:
    - port: {{ .Values.web.port }}         # 클라이언트가 접속할 포트
      targetPort: {{ .Values.web.port }}   # 파드 내부 포트와 동일하게 설정
