# Web 서버 설정
web:
  image: httpd:2.4
  port: 80
  replicas: 2
  efsMountEnabled: false
  service:
    type: LoadBalancer

# WAS 설정
was:
  image: stevekimbespin/petclinic_btc:latest
  port: 8080
  replicas: 2
  efsMountEnabled: true
  service:
    type: ClusterIP

# EFS 볼륨 설정
storage:
  # GitHub Actions 또는 --set 옵션으로 반드시 오버라이드해야 함
  volumeHandle: ""  # 기본값은 공백으로 설정
  accessModes:
    - ReadWriteMany
  size: 5Gi
  storageClassName: efs-sc

# PVC 설정
persistence:
  enabled: true
  existingClaim: petclinic-efs-pvc

#DB 설정
env:
  DB_HOST: "doit-baek-private-db.cbzhw40kmq8h.us-west-2.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "petclinic"
  DB_USERNAME: "admin"
  DB_PASSWORD: "password"  # 실제 배포 시 secretsManager 연동 필요

