# Web 서버 설정
web:
  image: httpd:2.4
  port: 80
  replicas: 2
  service:
    type: LoadBalancer

# WAS 설정
was:
  image: your-repo/petclinic:latest
  port: 8080
  replicas: 2

# EFS 볼륨 설정
storage:
  volumeHandle: fs-08fadcbeeacf5d6a1::fsap-02a9fdb29ebdffcf7
  accessModes:
    - ReadWriteMany
  size: 5Gi
  storageClassName: efs-sc
