# Web 서버 설정
web:
  image: httpd:2.4        # 프론트엔드 이미지
  port: 80

# WAS 설정
was:
  image: your-repo/petclinic:latest  # 백엔드 이미지
  port: 8080
  replicas: 2

# EFS 볼륨 설정 (자동 주입 대상)
storage:
  volumeHandle: fs-xxxxxxxxxxxxxxxxx  # GitHub Actions에서 --set으로 주입됨
  accessModes:
    - ReadWriteMany  # EFS는 다중 접근이 기본
  size: 5Gi
  storageClassName: efs-sc  # StorageClass 이름 (PV, PVC, SC에서 일치해야 함)
