apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-was
spec:
  replicas: {{ .Values.was.replicas }}
  selector:
    matchLabels:
      app: petclinic-was
  template:
    metadata:
      labels:
        app: petclinic-was
    spec:
      containers:
        - name: petclinic
          image: {{ .Values.was.image }}
          ports:
            - containerPort: {{ .Values.was.port }}
          env:
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: petclinic-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-secret
                  key: DB_PASSWORD
            - name: JAVA_OPTS
              value: "-Dspring.config.location=file:/app/config/"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
            {{- if .Values.was.efsMountEnabled }}
            - name: efs-logs
              mountPath: /app/logs
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: petclinic-config
        {{- if .Values.was.efsMountEnabled }}
        - name: efs-logs
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default "efs-pvc" }}
        {{- end }}
