apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-was
spec:
  replicas: {{ .Values.was.replicas }}
  selector:
    matchLabels:
      app: petclinic-was
  template:
    metadata:
      labels:
        app: petclinic-was
    spec:
      containers:
        - name: petclinic
          image: {{ .Values.was.image }}
          ports:
            - containerPort: {{ .Values.was.port }}
          {{- if .Values.was.efsMountEnabled }}
          volumeMounts:
            - name: efs-logs
              mountPath: /app/logs
          {{- end }}
      {{- if .Values.was.efsMountEnabled }}
      volumes:
        - name: efs-logs
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default "efs-pvc" }}
      {{- end }}
