apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-web
  template:
    metadata:
      labels:
        app: petclinic-web
    spec:
      containers:
        - name: apache
          image: {{ .Values.web.image }}
          ports:
            - containerPort: {{ .Values.web.port }}