apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /web
            pathType: Prefix
            backend:
              service:
                name: petclinic-web
                port:
                  number: 80
          - path: /was
            pathType: Prefix
            backend:
              service:
                name: petclinic-was
                port:
                  number: 8080