# EFS PersistentVolume 정의
# 실제 EFS 파일시스템과 연결되며, PVC가 이 PV를 Claim하여 사용합니다.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv  # 고정된 PV 이름 (PVC에서 참조 가능)
spec:
  capacity:
    storage: 5Gi  # 요구 용량 (EFS는 무제한이므로 실제로는 의미 없음)
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # 여러 Pod가 동시에 읽고 쓸 수 있음
  persistentVolumeReclaimPolicy: Retain  # 삭제 시 PV는 유지됨
  storageClassName: efs-sc  # StorageClass 참조
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxxxxxxx  # 실제 EFS 파일시스템 ID로 교체 필요
