# EFS PersistentVolume 정의
# Helm values.yaml에서 설정 값을 주입받아 동적으로 생성됩니다.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-efs-pv  # Helm 릴리스 이름 기반으로 PV 이름 동적 생성
spec:
  capacity:
    storage: {{ .Values.storage.size | default "5Gi" }}  # 의미 없는 값이지만 필수 입력
  volumeMode: Filesystem
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . }}
    {{- end }}
  persistentVolumeReclaimPolicy: Retain  # 삭제 후에도 PV 유지
  storageClassName: {{ .Values.storage.storageClassName | default "efs-sc" }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ required "❌ .Values.storage.volumeHandle 값이 설정되지 않았습니다!" .Values.storage.volumeHandle }}
