apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-efs-pvc
spec:
  volumeName: {{ .Release.Name }}-efs-pv
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . }}
    {{- end }}
  storageClassName: {{ .Values.storage.storageClassName | default "efs-sc" }}
  resources:
    requests:
      storage: {{ .Values.storage.size | default "5Gi" }}
