# EFS PersistentVolumeClaim 정의
# 이 PVC를 Pod에서 사용하면 efs-pv가 자동 연결됩니다.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.existingClaim | default "efs-pvc" }}  # 디폴트 이름
spec:
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . }}
    {{- end }}
  storageClassName: {{ .Values.storage.storageClassName | default "efs-sc" }}
  resources:
    requests:
      storage: {{ .Values.storage.size | default "5Gi" }}
