apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  db-username: {{ .Values.was.env.DB_USERNAME | quote }}
  db-password: {{ .Values.was.env.DB_PASSWORD | quote }}
