apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc  # PVC에서 참조할 이름
  annotations:
    meta.helm.sh/release-name: efs-storage
    meta.helm.sh/release-namespace: default
provisioner: efs.csi.aws.com  # Amazon EFS CSI 드라이버 사용
