apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc  # PVC에서 참조할 이름
provisioner: efs.csi.aws.com  # Amazon EFS CSI 드라이버
reclaimPolicy: Retain         # PVC 삭제 후에도 EFS 유지
volumeBindingMode: Immediate  # 즉시 바인딩
