# create-vpc.yaml 파일을 주석 포함하여 생성
yaml_with_comments = """\
# 이 워크플로는 GitHub Actions를 통해 VPC를 자동으로 배포하는 데 사용됩니다.
# 변경된 vpc-3tier.yaml 파일을 기반으로 CloudFormation 스택을 생성합니다.

name: Deploy VPC via CloudFormation

on:
  # 아래 파일 중 하나가 변경되면 워크플로 실행
  push:
    paths:
      - 'vpc-3tier.yaml'
      - '.github/workflows/create-vpc.yaml'
  # GitHub 웹 UI에서 수동 실행도 허용
  workflow_dispatch:

jobs:
  deploy:
    # 실행 환경: Ubuntu 최신 이미지 사용
    runs-on: ubuntu-latest

    steps:
    # Step 1: GitHub 리포지토리의 코드를 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: AWS 자격 증명 구성 (GitHub Secrets에서 읽음)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    # Step 3: CloudFormation을 사용하여 VPC 템플릿 배포
    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file vpc-3tier.yaml \
          --stack-name vpc-3tier-stack \
          --capabilities CAPABILITY_NAMED_IAM

    # Step 4: 스택 생성 이후 상태 확인
    - name: Describe Stack
      run: aws cloudformation describe-stacks --stack-name vpc-3tier-stack
"""

# 파일 저장 경로
file_path = "/mnt/data/create-vpc-with-comments.yaml"

# 파일 생성
with open(file_path, "w") as f:
    f.write(yaml_with_comments)

file_path
