name: Deploy VPC via CloudFormation

# GitHub Actions Workflow: CloudFormation 기반 VPC 자동 배포
# vpc-3tier.yaml 템플릿을 AWS CloudFormation으로 배포하여
# VPC, 서브넷, IGW 등 3티어 인프라를 구성합니다.

on:
  push:
    paths:
      - 'vpc-3tier.yaml'
      - '.github/workflows/create-vpc.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: GitHub 저장소 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: AWS 자격 증명 구성
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # Step 3: CloudFormation 스택 배포
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy             --template-file vpc-3tier.yaml             --stack-name vpc-3tier-stack             --capabilities CAPABILITY_NAMED_IAM

      # Step 4: 스택 상태 확인
      - name: Describe Stack
        run: aws cloudformation describe-stacks --stack-name vpc-3tier-stack
